#!/bin/bash

set -e

case $1 in
    configure)
        # Create a new system user to run the isolate-daemon
        adduser --quiet --system --ingroup adm cocaine

        # Set the correct permissions on the log directorye
        chown -R cocaine /var/log/ubic/cocaine-isolate-daemon
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with an unknown argument \`$1'" >&2
        ;;
esac

exit 0

